#!/bin/bash

IFS=$'\n'
wallpaper_directory="/home/yada/Pictures/catppuccin"
duration=300

[ -z "$wallpaper_directory" ] && echo "Usage: $(basename "$0") [DIRECTORY] [DURATION]" && exit 1
[ ! -d "$wallpaper_directory" ] && echo "Directory '$wallpaper_directory' does not exist" && exit 1
[ -z "$duration" ] && duration=60

# Loop through wallpapers
while true; do
	for file in "$wallpaper_directory"/*; do
		[ ! -f "$file" ] && continue

		mime_type=$(file --mime-type -b "$file")
		case "$mime_type" in
		image/jpeg | image/png | image/webp)
			echo "Setting wallpaper: $file"
			swww img "$file" \
				--transition-type fade \
				--transition-fps 60 \
				--transition-duration 1 \
				--transition-pos "$(hyprctl cursorpos 2>/dev/null || echo "0,0")"
			sleep "$duration"
			;;
		*)
			echo "Skipping unsupported file: $file"
			;;
		esac
	done
done
