#!/bin/bash

# Directory containing wallpapers
wallpaper_dir="$HOME/Pictures/wallpaper"

# Transition settings
transition_type="fade"
transition_duration=5

# Time between wallpaper changes (in seconds)
interval=300

# Main loop
while true; do
	img=$(find "$wallpaper_dir" -type f \( -iname '*.jpg' -o -iname '*.png' \) | shuf -n 1)

	swww img "$img" \
		--transition-type "$transition_type" \
		--transition-duration "$transition_duration" \
		--transition-fps 60

	sleep "$interval"
done
