import = [
    "~/.config/alacritty/themes/themes/kanagawa_wave.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
opacity = 0.85

decorations = "Buttonless"

[font]
normal.family = "CaskaydiaCove Nerd Font Mono"

#regular
size = 11.5

#for video
# size = 35.0
