general.import = [
    "~/.config/alacritty/themes/themes/themes/catppuccin_mocha.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
opacity = 0.85

decorations = "None"
startup_mode = "Fullscreen"

[font]
normal.family = "JetBrains Mono"

#regular
size = 10.5

#for video
# size = 35.0
