general.import = [
    "~/.config/alacritty/themes/themes/tokyo_night.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
opacity = 1

decorations = "None"

[font]
normal.family = "Iosevka Nerd Font"

#regular
size = 11.5

#for video
# size = 35.0


