general.import = [
    "~/.config/alacritty/themes/themes/themes/catppuccin_mocha.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 7
padding.y = 7

decorations = "None"
startup_mode = "Fullscreen"

[font]
normal.family = "Monolisa"

#regular
size = 11.5

#for video
# size = 35.0
